create table ingredient_dish
(
    id            bigint generated by default as identity,
    quantity      integer,
    dish_id       bigint,
    ingredient_id bigint,
    primary key (id)
);
alter table if exists ingredient_dish
    add constraint FK_dishes_ingredient_dish foreign key (dish_id) references dishes;
alter table if exists ingredient_dish
    add constraint FK_ingredients_ingredient_dish foreign key (ingredient_id) references ingredients;