create table dishes
(
    id   bigint generated by default as identity,
    name varchar(255),
    description varchar(255),
    cooking_time_minute integer,
    category_id bigint,
    primary key (id)
);
alter table if exists dishes
    add constraint FK_dishes_category foreign key (category_id) references categories;