create table ingredients
(
    id              bigint generated by default as identity,
    ingredient_name varchar(255),
    quantity        integer,
    dish_id         bigint,
    measurement_id  bigint,
    primary key (id)
);
create table measurements
(
    id         bigint generated by default as identity,
    conversion double precision,
    name       varchar(255),
    primary key (id)
);
alter table if exists ingredients
    add constraint FK_ingredients_dishes foreign key (dish_id) references dishes;
alter table if exists ingredients
    add constraint FK_ingredients_measurements foreign key (measurement_id) references measurements;