create table images
(
    id                 bigint generated by default as identity,
    bytes              oid,
    content_type       varchar(255),
    name               varchar(255),
    original_file_name varchar(255),
    size               bigint,
    dish_id            bigint,
    primary key (id)
);
alter table if exists images
    add constraint FK_images_dishes foreign key (dish_id) references dishes;